# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'testProject2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaoSDK'
  # Pods for testProject2

  target 'testProject2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
